# This is a basic workflow to help you get started with Actions

name: Scheduled Compiler

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0 0 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Load repo
        uses: actions/checkout@v3.0.0
        with:
          path: destination
      
      - name: Load List-KR
        uses: actions/checkout@v3.0.0
        with: 
          repository: 'List-KR/List-KR'
          path: original
      
      - name: Read the top filter file
        id: filter
        uses: juliangruber/read-file-action@v1.1.4
        with:
         # File path
          path: original/filter.txt
          
      - name: Process the list of files to access
        run: grep -e 'include' original/filter.txt | sed -n -e 's/^.*include //p'
